
# /Users/waziz/workspace/github/grasp/grasp/cfg/cfg_yacctab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '864FD74CA31879DABCEE0B46E6FA51C9'
    
_lr_action_items = {'$end':([1,10,11,12,14,15,16,18,],[0,-1,-11,-7,-6,-9,-8,-10,]),'BAR':([2,4,5,6,8,9,],[3,7,-3,-2,-5,-4,]),'EQUALS':([13,],[17,]),'TERMINAL':([3,4,5,6,8,9,],[6,9,-3,-2,-5,-4,]),'FVALUE':([7,10,11,12,14,15,16,17,18,],[11,11,-11,-7,-6,-9,-8,18,-10,]),'NONTERMINAL':([0,3,4,5,6,8,9,],[2,5,8,-3,-2,-5,-4,]),'FNAME':([7,10,11,12,14,15,16,18,],[13,13,-11,-7,-6,-9,-8,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rhs':([3,],[4,]),'rule':([0,],[1,]),'fpairs':([7,],[10,]),'fvalue':([7,10,],[12,15,]),'fpair':([7,10,],[14,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rule","S'",1,None,None,None),
  ('rule -> NONTERMINAL BAR rhs BAR fpairs','rule',5,'p_rule_and_weights','ply_cfg.py',88),
  ('rhs -> TERMINAL','rhs',1,'p_rhs','ply_cfg.py',103),
  ('rhs -> NONTERMINAL','rhs',1,'p_rhs','ply_cfg.py',104),
  ('rhs -> rhs TERMINAL','rhs',2,'p_rhs_recursion','ply_cfg.py',108),
  ('rhs -> rhs NONTERMINAL','rhs',2,'p_rhs_recursion','ply_cfg.py',109),
  ('fpairs -> fpair','fpairs',1,'p_fpairs','ply_cfg.py',113),
  ('fpairs -> fvalue','fpairs',1,'p_fpairs','ply_cfg.py',114),
  ('fpairs -> fpairs fpair','fpairs',2,'p_fpairs_recursion','ply_cfg.py',118),
  ('fpairs -> fpairs fvalue','fpairs',2,'p_fpairs_recursion','ply_cfg.py',119),
  ('fpair -> FNAME EQUALS FVALUE','fpair',3,'p_fpair','ply_cfg.py',123),
  ('fvalue -> FVALUE','fvalue',1,'p_fvalue','ply_cfg.py',127),
]
